language: java

install: true

jdk:
  - openjdk6

#addons:
#  apt:
#    packages:
#    - oracle-java6-installer
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - rm -rf $HOME/.gradle/
  - echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
#  - sudo update-java-alternatives -s java-6-oracle
  - java -version
  - chmod +x gradlew

script:
  - ./gradlew build --no-daemon
